version: '3.8'
services:
  assessment:
    container_name: app-assessment
    build: ./
    ports:
      - "8083:8083"
#    depends_on:
#      - mongo
#    networks:
#      - assessment-network
#
#  mongo:
#    image: mongo:latest
#    container_name: mongo-db
#    ports:
#      - "27018:27018"
#    networks:
#      - assessment-network
#    volumes:
#      - mongo-data:/data/db
#    restart: always

networks:
  assessment-network:
#
#volumes:
#  mongo-data:
#    driver: local
